name: Release & Publish

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    with:
      python-versions: '["3.10", "3.11", "3.12"]'
    secrets: inherit

  release:
    name: Semantic Release & Publish
    needs: run-tests
    environment: pypi
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to main branch
        run: |
          git checkout main
          git pull origin main

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: uv tool install poetry

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Version and Changelog (Local)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uvx --from "python-semantic-release>=9.0.0" semantic-release version

      - name: Commit changes (Local)
        run: |
          git add CHANGELOG.md pyproject.toml
          git diff --staged --quiet || git commit -m "chore: update changelog [skip ci]"

      - name: Push changes to GitHub
        run: git push origin main

      - name: Publish to Github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uvx --from "python-semantic-release>=9.0.0" semantic-release publish


      # - name: Build Package
      #   run: poetry build

      # - name: Publish to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/

      # - name: Publish to PyPI
      #   # Only publish if this isn't a pre-release (alpha/beta)
      #   if: "!contains(github.ref, 'alpha') && !contains(github.ref, 'beta') && !contains(github.ref, 'rc')"
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://upload.pypi.org/legacy/
      #     verbose: true
