name: GitHub Release Creator

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  tag:
    name: Semantic Tagging & Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write

    steps:
    - name: Checkout Repository on Correct Commit
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Attach HEAD to the 'main' branch
      run: |
        BRANCH_NAME=${{ github.event.workflow_run.head_branch }}
        git checkout $BRANCH_NAME
        echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry and Dependencies
      uses: snok/install-poetry@v1

    - name: Install Semantic Release
      run: poetry install --only dev

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Build Package Artifacts
      run: poetry build

    - name: Automated Version Bump, Changelog, and Tag Push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        poetry run semantic-release publish
